#storage class (identify the storage to use)
apiVersion: {{ .Values.storageClass.apiVersion }}
kind: {{ .Values.storageClass.kind }}
metadata:
  name: {{ .Values.storageClass.metadata.name }}
provisioner: {{ .Values.storageClass.provisioner }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }} #bind volume immediately
---
#persistent volume (define storage for mysql)
apiVersion: {{ .Values.persistentVolume.apiVersion }}
kind: {{ .Values.persistentVolume.kind }}
metadata:
  name: {{ .Values.persistentVolume.metadata.name }}
  labels:
    app: mysql
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
    - {{ toYaml .Values.persistentVolume.accessModes | indent 4 }} #volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain #retain volume after claim is deleted
  storageClassName: mysql-storage-class
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }} #path to the host directory taped minikube ssh to check your path
---
#persistent volume claim (request storage for mysql)
apiVersion: {{ .Values.pvc.apiVersion }}
kind: {{ .Values.pvc.kind }}
metadata:
  name: {{ .Values.pvc.metadata.name }}
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mysql-storage-class
---
#header - api version and kind
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.mysqlService.metadata.name }}"
  labels:
    app: "{{ .Values.mysqlService.metadata.name }}"
    tier: "{{ .Values.mysqlService.metadata.tier }}"
    version: "{{ .Values.mysqlService.metadata.version }}"
spec:
  ports:
  - port: {{ .Values.mysqlService.port }}
    protocol: TCP
    targetPort: {{ .Values.mysqlService.port }}
  selector:
    app: "{{ .Values.mysqlService.metadata.name }}"
    tier: "{{ .Values.mysqlService.metadata.tier }}"
  type: ClusterIP
---
#header - api version and kind

apiVersion: apps/v1
kind: Deployment

#metadata section with name, labels, and annotations
metadata:
  name: "{{ .Values.mysqlDeployment.labels.name }}"
  labels:
    app: "{{ .Values.mysqlDeployment.labels.name }}"
    tier: "{{ .Values.mysqlDeployment.labels.tier }}"
    version: "{{ .Values.mysqlDeployment.labels.version }}"
  annotations:
    description: "MySQL Deployment"
    maintainer: "Your Name <your.email@example.com>"
    documentation: "https://dev.mysql.com/doc/"
  finalizers:
    - foregroundDeletion

#deployment spec section
spec:
  replicas: {{ .Values.mysqlDeployment.spec.replicas }}
  revisionHistoryLimit: {{ .Values.mysqlDeployment.spec.revisionHistoryLimit | default 10 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  template: #pod details
    metadata:
      labels:
        app: mysql
        tier: database
        version: "8.0"
    spec:
      # securityContext:
      #   runAsUser: 999
      #   runAsGroup: 999
      #   runAsNonRoot: true
      #   fsGroup: 999
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: app-database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        volumeMounts: #mount persistent volume claim to /var/lib/mysql
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources: #Define pod resource requests and limits
          requests:
            memory: "256Mi" #debibytes/gibibytes
            cpu: "250m"     #millicores
          limits:
            memory: "512Mi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mysqladmin ping -h localhost -u root -pMYSQL_ROOT_PASSWORD
          initialDelaySeconds: 30 #wait 30 seconds after container starts before probing
          periodSeconds: 10       #probe every 10 seconds
          timeoutSeconds: 5       #probe times out after 5 seconds
          failureThreshold: 3     #after 3 failures, container is considered unhealthy
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30 #wait 30 seconds after container starts before probing
          periodSeconds: 10       #probe every 10 seconds
          timeoutSeconds: 5       #probe times out after 5 seconds
          failureThreshold: 3     #after 3 failures, container is considered unhealthy
      volumes: #define volumes for the pod
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
